services:
  - type: web
    name: hospital-management-api
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: hospital-db
    databaseName: hospital_management
    user: hospital_user
    plan: free